# Generated by Django 4.2.5 on 2023-09-16 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='details',
            field=models.CharField(max_length=800),
        ),
    ]
